### ISSUE TITLE
Trying to make a build for UE5.5

### ISSUE THREAD

**Issue by oivio** [Sixze/ALS-Refactored#577]
I did try to make a build with VS to latest UE5.5. 

Errors :

```
Plugins\ALS-Refactored\Source\ALS\Private\AlsCharacterMovementComponent.cpp(181): error C2065: 'bUseAccelerationForPaths': undeclared identifier
Plugins\ALS-Refactored\Source\ALS\Private\AlsCharacterMovementComponent.cpp(464): error C2664: 'FVector UCharacterMovementComponent::GetLedgeMove(const FVector &,const FVector &,const FFindFloorResult &) const': cannot convert argument 3 from 'const FVector' to 'const FFindFloorResult &'
Plugins\ALS-Refactored\Source\ALS\Private\AlsCharacterMovementComponent.cpp(464): note: Reason: cannot convert from 'const FVector' to 'const FFindFloorResult'
Plugins\ALS-Refactored\Source\ALS\Private\AlsCharacterMovementComponent.cpp(464): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called

1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\GameFramework\CharacterMovementComponent.h(1796): note: see declaration of 'UCharacterMovementComponent::GetLedgeMove'
Plugins\ALS-Refactored\Source\ALS\Private\AlsCharacterMovementComponent.cpp(464): note: while trying to match the argument list '(const FVector, const FVector, const FVector)'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2641: cannot deduce template arguments for 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(FIntrusiveUnsetOptionalState)': expects 1 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(696): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(TArray<OtherElementType,InAllocatorType> &&,InAllocatorType::SizeType)': expects 2 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(661): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(TArray<OtherElementType,OtherAllocator> &&)': expects 1 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(645): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(TArray<T,AllocatorType> &&)': expects 1 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(630): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(const TArray<T,AllocatorType> &,InAllocatorType::SizeType)': expects 2 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(464): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(const TArray<T,AllocatorType> &)': expects 1 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(452): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(const TArray<OtherElementType,OtherAllocator> &)': expects 1 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(442): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(std::initializer_list<_Elem>)': expects 1 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(424): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(const TArrayView<OtherElementType,OtherSizeType> &)': expects 1 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(419): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(const InElementType *,InAllocatorType::SizeType)': expects 2 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(405): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(void)': expects 0 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(393): note: see declaration of 'TArray'
Plugins\ALS-Refactored\Source\ALS\Private\Nodes\AlsRigUnits.cpp(103): error C2780: 'TArray<T,AllocatorType> TArray(TArray<T,AllocatorType>)': expects 1 arguments - 3 provided
1>C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Core\Public\Containers\Array.h(369): note: see declaration of 'TArray'
```

**Comment by ameaninglessname** [comment]
You could try [5.5 branch](https://github.com/Sixze/ALS-Refactored/tree/ue-5.5)
